version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: content
    env_file:
      - ./.env
    ports:
      - 5432:5432
    expose:
      - 5432
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web
  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    environment:
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    expose:
      - 9200
    depends_on:
      - web
  redis:
    image: redis:6.0
    container_name: redis
    expose:
      - 6379
  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - elasticsearch
      - redis
      - web
    env_file:
      - ./.env
  auth:
    build:
      context: ./auth_api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=content
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - SECRET_KEY=16be489f7ba8a18ab6d506a207dde676a56bc7684b1a16120d4d432b19f3a8cd
      - JWT_SECRET_KEY=16be489f7ba8a18ab6d506a207dde676a56bc7684b1a16120d4d432b19f3a8cd
      - JWT_ACCESS_TOKEN_EXPIRES_HOURS=1
      - JWT_REFRESH_TOKEN_EXPIRES_DAYS=30
volumes:
  postgres_data:
  static_volume:
  media_volume: