version: '3.8'

services:
  # frontend:
  #     build:
  #       context: ./frontend
  #       dockerfile: Dockerfile
  #     container_name: frontend
  #     expose:
  #       - 3000
  #     stdin_open: true
  #     volumes:
  #       - ./frontend:/app
  #       - '/app/node_modules'
  #     env_file:
  #       - .env
  #     environment:
  #       - CHOKIDAR_USEPOLLING=true
  search_api:
    build:
      context: ./search_api
      dockerfile: Dockerfile
    container_name: search_api
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - .env
    depends_on:
      - postgres
  
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres_sprint6
    restart: always
    volumes:
      - .postgres_data/data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: content
    env_file:
      - .env
    expose:
      - 5432
  # nginx:
  #   build: ./nginx
  #   container_name: nginx
  #   volumes:
  #     - static_volume:/home/app/web/staticfiles
  #     - media_volume:/home/app/web/mediafiles
  #     - frontend_volume:/home/app/build
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - search_api
  #     - frontend
  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    environment:
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    expose:
      - 9200
    depends_on:
      - search_api
  redis:
    image: redis:6.0
    container_name: redis
    expose:
      - 6379
  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    container_name: etl
    depends_on:
      - postgres
      - elasticsearch
      - redis
      - search_api
    env_file:
      - .env
  auth_api:
    build:
      context: ./auth_api
      dockerfile: Dockerfile
    container_name: auth_api
    #expose: 
    #  - 5001
    ports:
      - 5001:5001
    env_file:
      - .env
  swagger_ui_auth:
   image: swaggerapi/swagger-ui
   container_name: swagger_ui_authcontainer
   ports:
      - 8080:8080
   volumes:
      - ./auth_api/flauth/swagger.yaml:/usr/share/nginx/html/doc/swagger.yaml
   environment:
      API_URL: doc/swagger.yaml
  
  role_api:
    build:
      context: ./role_api
      dockerfile: Dockerfile
    container_name: role_api
    expose: 
      - 5002
    env_file:
      - .env

  tests:
    build:
      context: ./tests/functional
      dockerfile: Dockerfile
    container_name: tests
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
  media_volume:
  frontend_volume:
