openapi: 3.0.3

info:
  title: Auth API
  version: '1.0'
  description: API for signup, login and auth users

paths:
  /login:
    post:
      operationId: auth.login_post
      summary: Return the access and refresh tokens
      
      parameters:
        - $ref: '#/components/parameters/Login'
        - $ref: '#/components/parameters/Password'
    
      responses:
        200:
          description: Succesuful returned tokens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
        400: 
          description: Login does not exist
        401:
          description: A wrong password
          
  /login/{page}:
    get:
      security:
        - AccessToken: []

      operationId: auth.info_get
      summary: Information about auth jwt is nedded
      
      parameters:
        - in: path
          name: page
          required: true
          schema:
            type: integer
          description: Page for pagination
      
      responses:
        200:
          description: Auth records
          content:
            application/json:
              schema:
                $ref: '#/components/parameters/Login'
          
  /signup:
    post:
      operationId: auth.signup_post
      summary: Create a new user
      
      parameters:
        - $ref: '#/components/parameters/Login'
        - $ref: '#/components/parameters/Email'
        - $ref: '#/components/parameters/Name'
        - $ref: '#/components/parameters/Password'
      
      responses:
        201:
          description: Successful registration
        409: 
          description: Login or E-mail already exists
  
  /refresh:
    put:
      security:
        - RefreshToken: []
      
      operationId: auth.refresh_post
      summary: Check the refresh tocken from header, give new access and refresh token
      
      responses:
        200:
          description: Return tokens
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/AythRecords'
        401:
          description: Wrong token

  /logout:
    delete:
      security:
        - AccessToken: []
      
      operationId: auth.logout
      summary: Clean tokens
      
      responses:
        200:
          description: Access and refresh token delete
        401:
          description: Wrong token

  /newlogin:
    put:
      operationId: auth.newlogin_post
      summary: Change login
      
      parameters:
        - $ref: '#/components/parameters/Login'
        - $ref: '#/components/parameters/NewLogin'
        - $ref: '#/components/parameters/Password'

      responses:
        200:
          description: New login set
        404:
          description: Login dose not exist
        401:
          description: Wrong password

  /user:
    put:
      operationId: auth.newpasswor_post
      summary: Change password

      parameters:
        - $ref: '#/components/parameters/Login'
        - $ref: '#/components/parameters/NewPassword'
        - $ref: '#/components/parameters/Password'

      responses:
        200:
          description: New password set
        409: 
          description: New login already exists
        404:
          description: Login dose not exist
        401:
          description: Wrong password
          
components:
  schemas:
    Tokens:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string

    AythRecords:
      type: array
      items:
        type: object
        properties:
          user_agent:
            type: string
            description: User agent
            example: "Chrome"
          date_time:
            type: string
            format: date-time
            description: Event time
            example: "2015-07-07T15:49:51.230+02:00"

  parameters:
    Login:
      name: login
      description: User login
      in: query
      schema:
        type: string
        pattern: "^[a-zA-Z0-9-]+$"
      required: true
  
    Name:
      name: login
      description: User login
      in: query
      schema:
        type: string
        pattern: "^[a-zA-Z0-9-]+$"
      required: true

    Password:
      name: password
      description: User password
      in: query
      schema:
        type: string
      required: true

    Email:
      name: email
      description: User email
      in: query
      schema:
        type: string
      required: true

    NewLogin:
      name: new_login
      description: New user login
      in: query
      schema:
        type: string
        pattern: "^[a-zA-Z0-9-]+$"
      required: true

    NewPassword:
      name: new_password
      description: New user pasword
      in: query
      schema:
        type: string
      required: true
      
  securitySchemes:
    AccessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
    RefreshToken:
      type: http
      scheme: bearer
      bearerFormat: JWT