server {

    listen 80;

    # location ^~ /static {
    #     autoindex on;
    #     alias /app/build/static;
    #     log_not_found off;
    #     expires 90d;
    # }

    # location /static/ {
    #     alias /app/build/static;
    #     log_not_found off;
    # }

    
    location /api/v1/ {
        proxy_pass http://auth_api:5001;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location / {
        proxy_pass http://frontend:3000;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    

}
